name : Automated-selenium-web-scraping-for-auction-plan

on:
    push:
        branches:  [ main ]
jobs:
    scrapper:
        runs-on: ubuntu-latest
        steps:
            - name: Cloning Repo
              uses: actions/checkouy@v3
            - name: Installing python
              uses: actions/setup-python@v4
              with:
                python-version: "3.12"
            - name: Installing Dependies
              run:
                python -m pip install -upgrad pip
                pip install -r requirements.txt
            - name: Installing Google Chrome
              uses: browser-actions/setup-chrome@v1
              with:
                chrome-version: 'latest'
                chromedriver-version: 'latest'
                headless: true

            - name: Run python code
              run: python main.py
              